### ISSUE TITLE
Fresh install server error on login (missing static files for d3.js)

### ISSUE THREAD

**Issue by sudopseudocode** [wger-project/docker#109]
After doing a fresh install per the prod.env & compose files recommendations, everything appears to be running successfully. Postgres, Redis, and even the static and media files are correctly being served via my reverse proxy (using Caddy). After running the `manage.py sync-exercises`, `manage.py download-exercise-images`, `manage.py download-exercise-videos`, and `wger load-online-fixtures`, I can see the home page loading in my browser and everything appears as expected.

Once I click "login", I get the client side error message that an error occurred. In the wger server container, I see the following error logs:
```
  File "/home/wger/.local/lib/python3.12/site-packages/compressor/base.py", line 191, in get_filename
    raise UncompressableFileError(
compressor.exceptions.UncompressableFileError: 'yarn/d3/dist/d3.js' could not be found in the COMPRESS_ROOT '/home/wger/static' or with staticfiles.
```

What's interesting is that I am not even seeing d3 listed in the wger server's package.json.
This error goes away if I copy a `node_modules/d3` folder (installed from a separate workspace, since the docker image does not have `yarn`/`node`/`npm` installed out of the box) into the corresponding bind mount for `/home/wger/static/yarn`. This hacky fix let's me get past the login page and everything else appears to behave as expected at that point.

Any idea why this isn't correctly handled by the wger server initial set up? It seems other js & css static files are being correctly generated.

**Comment by rolandgeider** [comment]
omg, that is ineed unbelievable hacky! 😆  D3 was recently removed in favor of another charting library, seems I didn't remove the link from all the templates, I have updated the images, if you pull it should work again

**Comment by sudopseudocode** [comment]
Haha amazing, glad it was a simple fix. Just pulled and looks like that did the trick. Thanks!
