### ISSUE TITLE
Video 413 Request Entity Too Large

### ISSUE THREAD

**Issue by DunklerPhoenix** [wger-project/docker#23]
## Steps to Reproduce

1. activate Videoupload in wger Docker
2. Try upload a video
3. get  413

**Expected results:** 
working videoupload

**Actual results:** 
Limited file size by nginx setting

Needs some additional command in nginx wger folder for higher bodysize limit

https://github.com/wger-project/wger/issues/1014

**Comment by DunklerPhoenix** [comment]
I added at the end of my nginx.conf from this repo now:
```
# set client body size to 100M #
client_max_body_size 100M;
```

**Comment by rolandgeider** [comment]
Good catch! How big was the file you were trying to upload?

**Comment by DunklerPhoenix** [comment]
0,8mb. The default value of nginx is about 2mb for the complete request
