### ISSUE TITLE
WGER does not display correctly

### ISSUE THREAD

**Issue by SuperDarius-git** [wger-project/docker#30]
Good day

I do not know if this issue has been raised, and I do not know how to search for it. I am running wger in docker, but all of a sudden it looks like the attached photo.  Please help. I can't seem to fix it. It looks like it doesn't see or load the CSS on the page, but I'm not sure. It happens in all browsers, so it's not a plugin causing it.

![image](https://user-images.githubusercontent.com/29814230/185544318-aad1b61d-fc35-4519-a243-ce0be71d9f14.png)

Thank you
Darius

**Comment by rolandgeider** [comment]
Hi! Yeah, there's something with the static files. Are you using the regular docker compose or did you change something?

**Comment by gassssss** [comment]
Same thing is happening to me, and I did change some things from the provided docker file to adjust to my current home dockers. I'm using traefik as a reverse proxy and let's encrypt, also using an already present postgres container.

As @SuperDarius-git says, the server spits an error when trying to find anything under '/home/wger/static/'

**Comment by rolandgeider** [comment]
@gassssss did this also suddenly started happening?

For a bit of background, django doesn't serve any static files during production, this needs to be done by another server (it could be something like a CDN, an S3 bucket, etc.). Django collects all static assets and copies them to, in our case, a folder in a docker volume that is then read by an nginx.

I'm not sure why this stopped working for you guys, but perhaps nuking the volume could help, this is repopulated on startup.

**Comment by gassssss** [comment]
Hi, no for me it's a new install, I was looking to solve it and just found this issue that has been just opened so I jumped in. In my case so I just see what the screenshot shows above, unformatted text and no images/resources at all.

But now that you pointed out that it serves no static content I see what the problem is... obviously user error. I didn't config nginx container because I thought it was there just to do reverse proxy and I simply skipped it all without even looking at it, it also serves the static files...

My sincere apologies and thanks a lot for the promptly answer.

**Comment by rolandgeider** [comment]
yeah, it's there for a reason 😄 The first times handling static files with django is always _fun_  (and don't worry about asking!)

**Comment by SuperDarius-git** [comment]
Yeah, thank you so much for the speedy replies... I am not familiar with Django AT ALL! Please guide me through the solution?

Thanks
Darius

**Comment by rolandgeider** [comment]
@SuperDarius-git if you use the regular config, everything is already configured, but there might be some folders that got out of sync or something. Could you stop the containers, do a `docker volume rm docker_static`, start everything again and post the logs if it still doesn't work?

It should look like this: 

```
wger_nginx | 2022/08/19 12:24:02 [notice] 1#1: start worker process 40
wger_nginx | 2022/08/19 12:24:02 [notice] 1#1: start worker process 41
wger_server | yarn install v1.22.19
wger_server | [1/5] Validating package.json...
wger_server | [2/5] Resolving packages...
wger_server | [3/5] Fetching packages...
wger_server | [4/5] Linking dependencies...
wger_server | [5/5] Building fresh packages...
wger_server | Done in 5.22s.
wger_server | yarn run v1.22.19
wger_server | $ sass wger/core/static/scss/main.scss:wger/core/static/yarn/bootstrap-compiled.css
wger_server | Done in 1.73s.
wger_server | Running in production mode, running collectstatic now
wger_server | 
wger_server | 5723 static files copied to '/home/wger/static', 302 unmodified.
wger_server | Performing database migrations
wger_server | Operations to perform:
```

**Comment by SuperDarius-git** [comment]
Ok, so this is what it looks like:

```
yarn install v1.22.19
,
[1/5] Validating package.json...
,
[2/5] Resolving packages...
,
[3/5] Fetching packages...
,
[4/5] Linking dependencies...
,
[5/5] Building fresh packages...
,
Done in 22.57s.
,
yarn run v1.22.19
,
$ sass wger/core/static/scss/main.scss:wger/core/static/yarn/bootstrap-compiled.css
,
Done in 7.66s.
,
Running in production mode, running collectstatic now,
,
6025 static files copied to '/home/wger/static'.,
Performing database migrations,
Operations to perform:,
  Apply all migrations: auth, authtoken, config, contenttypes, core, easy_thumbnails, exercises, gallery, gym, mailer, manager, measurements, nutrition, sessions, sites, weight,
Running migrations:,
  No migrations to apply.,
Set site URL to http://fit.super.org.za,
Using gunicorn...,
[2022-08-19 12:40:56 +0000] [86] [INFO] Starting gunicorn 20.1.0,
[2022-08-19 12:40:56 +0000] [86] [INFO] Listening at: http://0.0.0.0:8000 (86),
[2022-08-19 12:40:56 +0000] [86] [INFO] Using worker: sync,
[2022-08-19 12:40:56 +0000] [87] [INFO] Booting worker with pid: 87,
```

**Comment by rolandgeider** [comment]
mhhh

I mean, at least everything is getting collected correctly, but why isn't it serving anything? Did you perhaps change some paths in the env file?

**Comment by SuperDarius-git** [comment]
I only changed my timezone, my site_url, email address and DJango DB Password...

**Comment by gassssss** [comment]
May I suggest checking the docker-compose and nginx.conf 

```
upstream wger {
    server web:8000; ## <-- "web" has to be the same name as the actual wger container or it's "domainname" in case you put one in there
...
```

```
services:
  web: ## <- same as this
    image: wger/server:latest
    container_name: wger_server
```

I myself made this mistake while setting it up, check just in case.

**Comment by SuperDarius-git** [comment]
It all seems correct, if I understand you correctly.

> May I suggest checking the docker-compose and nginx.conf
> 
> ```
> upstream wger {
>     server web:8000; ## <-- "web" has to be the same name as the actual wger container or it's "domainname" in case you put one in there
> ...
> ```
> 
> ```
> services:
>   web: ## <- same as this
>     image: wger/server:latest
>     container_name: wger_server
>     domainname: wger.ghl ## <--- or this if you have it, either should work
> ...
> ```
> 
> I myself made this mistake while setting it up, check just in case.

**Comment by gassssss** [comment]
Could you try `docker logs nginx` and then reload the site and check if there is any error or anything in nginx container logs?

**Comment by rolandgeider** [comment]
might there be some permission errors so that nginx can't access them?

**Comment by SuperDarius-git** [comment]
This is my Nginx logs:

```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration,
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/,
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh,
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf,
10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version,
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh,
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh,
/docker-entrypoint.sh: Configuration complete; ready for start up,
2022/08/19 12:40:11 [notice] 1#1: using the "epoll" event method,
2022/08/19 12:40:11 [notice] 1#1: nginx/1.22.0,
2022/08/19 12:40:11 [notice] 1#1: built by gcc 10.2.1 20210110 (Debian 10.2.1-6) ,
2022/08/19 12:40:11 [notice] 1#1: OS: Linux 5.15.0-46-generic,
2022/08/19 12:40:11 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576,
2022/08/19 12:40:11 [notice] 1#1: start worker processes,
2022/08/19 12:40:11 [notice] 1#1: start worker process 30,
2022/08/19 12:40:11 [notice] 1#1: start worker process 31,
```

**Comment by rolandgeider** [comment]
And when you open the application? specially the requests going to `/static`

**Comment by SuperDarius-git** [comment]
There are no extra logs when I try to open the application?

**Comment by SuperDarius-git** [comment]
It's installed on a VPS with a domain name and a subdomain through a NGINX Reverse Proxy server, with a Let's Encrypt certificate. Do you think any of those might be the reason? I also use port 830 instead of 8000 as setup in the Docker Compose file.

**Comment by rolandgeider** [comment]
Port 8000 is only used internally within the containers, you should change port 80! (I don't think you need to change anything else to expose the whole application on another port)

In any case try to access the docker compose setup as directly as possible and then add more and more layers (like your reverse proxy, HTTPS, etc)

**Comment by gassssss** [comment]
How did you went about nginx and wger?, did you just created another nginx container or updated the one you had with the new stuff from wger?
Did you also update the nginx.conf "upstream" with the 830 port?

**Comment by SuperDarius-git** [comment]
> How did you go about nginx and wger?, did you just created another nginx container or updated the one you had with the new stuff from wger? Did you also update the nginx.conf "upstream" with the 830 port?

I tried to change the upstream port in the NGINX.conf file, but no luck... It is different nginx containers.

**Comment by rolandgeider** [comment]
> I tried to change the upstream port in the NGINX.conf file, but no luck... It is different nginx containers. Also thank you so much for the help so far!

yeah, you should change it in the docker-compose file only (so e.g. 830:80)

**Comment by SuperDarius-git** [comment]
It says in the compose file 8000:8000, which I changed to 830:8000

What is this line? and how must I change this lines:
```
healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8000
```

Can't that be a reason?

**Comment by gassssss** [comment]
That line is checking that the server is alive, is internal to the container, doesn't really leave it, and that line is not essential either, I don't think that's the issue, but you can try commenting it out and relaunching it.

**Comment by SuperDarius-git** [comment]
Thank you all for your help. I will go on troubleshooting and posting on here tomorrow. In the meantime, I will try installing wger on another server and let you all know.

Thanks again...
Darius

**Comment by rolandgeider** [comment]
BTW, the line I mean is this one

https://github.com/wger-project/docker/blob/master/docker-compose.yml#L40

Let's hope we can get this working ✌🏻

**Comment by SuperDarius-git** [comment]
PROBLEM SOLVED!!!!!!I couldn't go to bed, it kept bothering me! So I got @rolandgeider last post and I realised I changed the wrong port to 830... Thank you to everyone who helped!

Thank you
Darius

**Comment by rolandgeider** [comment]
🥳
