### ISSUE TITLE
Verification emails use localhost instead of SITE_URL

### ISSUE THREAD

**Issue by zero-thermo** [wger-project/docker#47]
In `prod.env`, I have `SITE_URL=https://wger.mydomain.tld`. This is in a LAN-only environment with local reverse proxy.   

I also have SMTP variables correctly setup:

    ENABLE_EMAIL=True
    EMAIL_HOST=smtp.mailgun.org
    EMAIL_PORT=587
    EMAIL_HOST_USER=user@mydomain.tld
    EMAIL_HOST_PASSWORD=mypassword
    EMAIL_USE_TLS=True
    EMAIL_USE_SSL=False

Verification emails are successfully sent, but the "click here" link uses `localhost` instead of `SITE_URL`:

    http://localhost/email/email/long_email_verification_string

Replacing `localhost` with `wger.mydomain.tld` (SITE_URL) correctly loads the page and verifies the user.

Is this a bug, or have I missed a setting?

**Comment by rolandgeider** [comment]
Mhhh, I will have to check, but setting SITE_URL should be enough

**Comment by rolandgeider** [comment]
you're right, it was always set to localhost. I'll push a fix later today
