### ISSUE TITLE
Exercises Not Syncing

### ISSUE THREAD

**Issue by hherrera1229** [wger-project/docker#49]
Hello,

I'm having a similar issue as #36 but the steps used to resolve the error don't seem to be fully working for me. Not sure what to do next any info would be greatly appreciated! Logs from the docker container:

`yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
[5/5] Building fresh packages...
Done in 7.11s.
yarn run v1.22.19
$ sass wger/core/static/scss/main.scss:wger/core/static/yarn/bootstrap-compiled.css
Done in 3.52s.
Running in production mode, running collectstatic now
5726 static files copied to '/home/wger/static', 10012 unmodified.
Synchronizing exercises
*** Synchronizing languages...
done!
*** Synchronizing categories...
done!
*** Synchronizing muscles...
done!
*** Synchronizing equipment...
done!
*** Synchronizing exercises...
updated exercise cfb6a754-57be-431b-b8d0-d9963120bd5a
- updated translation cs 0fe97ed6-7d37-444c-90b6-f855cea68a6f - Barbell Wrist Curl
- updated translation ca 5afb7241-2eb9-4c9e-aa8f-b0b9bc8a0797 - Handgelenkstreckung
updated exercise 1b020b3a-3732-4c7e-92fd-a0cec90ed69b
- updated translation cs c788d643-150a-4ac7-97ef-84643c6419bf - 2 Handed Kettlebell Swing
updated exercise f2733700-aa5d-4df7-bc52-1876ab4fb479
- updated translation cs 6add5973-86d0-4543-928a-6bb8b3f34efc - Axe Hold
- updated translation ca 8e9d8968-323d-468c-9174-8cf11a105fad - Axe Hold
updated exercise 03db11cc-8079-463c-9399-6f346b100ce6
- updated translation cs 60d8018d-296f-4c62-a80b-f609a25d34ea - Abdominal Stabilization
- updated translation ca c659577f-d9de-4e39-bcd1-1b0bf1f62d11 - Bauch Stabilisation
updated exercise ea63d85c-8579-4dda-b99f-c4c8930f9af6
- updated translation cs 51595d74-afe2-4445-88ec-2a289251e710 - Tricep Pushdown on Cable
updated exercise 9e6dae29-5d03-440a-bdf1-2cb25a5179c2
- updated translation ru 4ef74871-44bb-43b3-acfb-8c221ad06bd2 - Adım atma
- updated translation sv f8720d72-e04e-4008-bdae-77d791d26ae4 - Marches
- updated translation fr 2c500679-beaa-4717-baf8-b2eab2b1bc89 - Opstappen
- updated translation it 1155ce91-a11b-488d-8751-ffb0e403fcbe - Progressos
- updated translation ca 1cc35af7-6ddf-4a1c-82f3-1974087cb2ee - Steigungen
- updated translation tr a35e8b34-4c04-47ea-bf71-e19af6872dda - Step
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 929, in get_or_create
    return self.get(**kwargs), False
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
wger.exercises.models.exercise.Exercise.DoesNotExist: Exercise matching query does not exist.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/base.py", line 306, in _commit
    return self.connection.commit()
psycopg2.errors.ForeignKeyViolation: insert or update on table "exercises_exercise" violates foreign key constraint "exercises_exercise_language_id_9675c687_fk_core_language_id"
DETAIL:  Key (language_id)=(23) is not present in table "core_language".
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/wger/src/manage.py", line 25, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/home/wger/src/wger/exercises/management/commands/sync-exercises.py", line 106, in handle
    self.sync_exercises()
  File "/home/wger/src/wger/exercises/management/commands/sync-exercises.py", line 146, in sync_exercises
    translation, translation_created = Exercise.objects.get_or_create(
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 934, in get_or_create
    with transaction.atomic(using=self.db):
  File "/usr/local/lib/python3.10/dist-packages/django/db/transaction.py", line 262, in __exit__
    connection.commit()
  File "/usr/local/lib/python3.10/dist-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/base.py", line 330, in commit
    self._commit()
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/base.py", line 305, in _commit
    with self.wrap_database_errors:
  File "/usr/local/lib/python3.10/dist-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/base.py", line 306, in _commit
    return self.connection.commit()
django.db.utils.IntegrityError: insert or update on table "exercises_exercise" violates foreign key constraint "exercises_exercise_language_id_9675c687_fk_core_language_id"
DETAIL:  Key (language_id)=(23) is not present in table "core_language".
Downloading exercise images
*** Processing images ***
*** Page 1
Processing image ef0b00e2-3323-4e7f-88fe-d71ef34b3384
    Remote exercise base not found in local DB, skipping...
Processing image bed4f21b-28be-4ef1-bd88-1a4e3db66c5c
    Remote exercise base not found in local DB, skipping...
Processing image 59efcec2-a7ce-40ba-bf2b-1a6eabe52fbd
    Remote exercise base not found in local DB, skipping...
Processing image 1c37e4e1-5144-4a50-8294-16180a9bc767
    Remote exercise base not found in local DB, skipping...
Processing image 065f9418-6245-46ae-8e24-b4013ce084e4
    Remote exercise base not found in local DB, skipping...
Processing image ca71df8e-a6d6-453f-a25a-f4cebae3b970
    Image not found in local DB, creating now...
    successfully saved
Processing image 7276a19e-06d0-45ae-a2a3-569bed75686b
    Image not found in local DB, creating now...
    successfully saved
Processing image c64a9199-5ad7-4552-abdd-491deb02296a
    Remote exercise base not found in local DB, skipping...
Processing image dd0a0445-11cf-45d3-bbd1-6ae0add6b39c
    Remote exercise base not found in local DB, skipping...
Processing image f22c1928-fc70-4595-b090-af73e7a019fe
    Remote exercise base not found in local DB, skipping...
Processing image aa574839-4a7e-4c0d-ac72-2f7448478a1c
    Remote exercise base not found in local DB, skipping...
Processing image 4545b1ab-bf7f-4626-894e-b801047f2fa9
    Remote exercise base not found in local DB, skipping...
Processing image f3ea8468-02df-4022-a8ef-17700c98d63c
    Remote exercise base not found in local DB, skipping...
Processing image ad26f561-e80b-43e2-93ed-07c0fba63a3d
    Remote exercise base not found in local DB, skipping...
Processing image a02c9c7d-f42d-43e0-9946-1b99b014daee
    Remote exercise base not found in local DB, skipping...
Processing image 08517378-bc36-4f6b-9952-1f45a02d936e
    Remote exercise base not found in local DB, skipping...
Processing image 6c1a7459-266d-491a-bd50-7cbaea2bc771
    Remote exercise base not found in local DB, skipping...
Processing image 94347272-2ea7-407f-9362-cde777bc908d
    Remote exercise base not found in local DB, skipping...
Processing image 63da5c54-7f1d-4a09-9867-2bdda2a6ddeb
    Remote exercise base not found in local DB, skipping...
Processing image 90e32fa6-a90d-46b3-8ea8-c9ec8e666eca
    Remote exercise base not found in local DB, skipping...
*** Page 2
Processing image c74c43a5-da29-443d-895c-2900b5591cd2
    Remote exercise base not found in local DB, skipping...
Processing image ed7c3729-22ce-425e-a0ad-108963a35c7a
    Remote exercise base not found in local DB, skipping...
Processing image 285943a6-e0ce-47cc-b244-ba698377af93
    Remote exercise base not found in local DB, skipping...
Processing image 4ddb899f-0acb-46b3-b110-d0aac701bc60
    Remote exercise base not found in local DB, skipping...
Processing image 40212645-0278-4c1d-9f7a-a00ee4d12314
    Remote exercise base not found in local DB, skipping...
Processing image 87a312b7-d01e-4f69-9bda-1ed2f1fcd9ab
    Remote exercise base not found in local DB, skipping...
Processing image 06cba35d-3c10-4e13-ae1c-524dbb194fdf
    Remote exercise base not found in local DB, skipping...
Processing image 8d42f527-b6ca-4749-9db9-94af1413cc2c
    Remote exercise base not found in local DB, skipping...
Processing image b0e8b77a-97c2-470f-9fc0-928ffb2aae89
    Remote exercise base not found in local DB, skipping...
Processing image 17e5d7a3-d94c-41dd-830d-15a5e1834dff
    Remote exercise base not found in local DB, skipping...
Processing image 1503e8e3-b67a-4e74-b044-99288eb26f44
    Remote exercise base not found in local DB, skipping...
Processing image 3cc89c05-19fe-4598-bb0c-24d36ef9c1d6
    Remote exercise base not found in local DB, skipping...
Processing image 70761be3-c07e-4dac-a0a6-b62b4e3c0ab6
    Remote exercise base not found in local DB, skipping...
Processing image c69477af-3337-46f1-819d-73a10c51e136
    Remote exercise base not found in local DB, skipping...
Processing image c0e334a0-25f4-4057-8dee-c6efeeabcf13
    Remote exercise base not found in local DB, skipping...
Processing image 10975be2-fbb5-40ea-8c72-22f7466d9e5a
    Remote exercise base not found in local DB, skipping...
Processing image d3e26e7c-7ef6-443d-a2bf-5b0a06fe2d29
    Remote exercise base not found in local DB, skipping...
Processing image deeecd20-53f7-4494-a531-e6ff8cd79045
    Remote exercise base not found in local DB, skipping...
Processing image a067edbd-c5e9-42be-8ce3-238c0a4760f6
    Remote exercise base not found in local DB, skipping...
Processing image 66ff858e-3719-4fdc-9710-c41e43a3c057
    Remote exercise base not found in local DB, skipping...
*** Page 3
Processing image 0aecd2f4-3016-4813-b3c0-6a708ae7069a
    Remote exercise base not found in local DB, skipping...
Processing image 4371e111-5b1f-4679-968e-bb5d9a48ebe2
    Remote exercise base not found in local DB, skipping...
Processing image fd35994a-70b4-4ca4-b236-12c178062996
    Remote exercise base not found in local DB, skipping...
Processing image 1fbfbec9-2431-45db-8ca7-a8e477add80f
    Remote exercise base not found in local DB, skipping...
Processing image aa645b51-beb3-4397-94d6-d1abee8be6db
    Remote exercise base not found in local DB, skipping...
Processing image e07c2ca5-a85f-4921-b590-39de7aa9b62a
    Remote exercise base not found in local DB, skipping...
Processing image 34600351-8b0b-4cb0-8daa-583537be15b0
    Remote exercise base not found in local DB, skipping...
Processing image 2fc242d3-5bdd-4f97-99bd-678adb8c96fc
    Remote exercise base not found in local DB, skipping...
Processing image 2e959dab-f39b-4c7c-9063-eb43064ab5eb
    Remote exercise base not found in local DB, skipping...
Processing image 74affc0d-03b6-4f33-b5f4-a822a2615f68
    Remote exercise base not found in local DB, skipping...
Processing image ad724e5c-b1ed-49e8-9279-a17545b0dd0b
    Remote exercise base not found in local DB, skipping...
Processing image 119e6823-6960-4341-a9e1-aaf78d7fb57c
    Remote exercise base not found in local DB, skipping...
Processing image 783d980c-af07-4ac0-a525-6dc8c426a204
    Remote exercise base not found in local DB, skipping...
Processing image f934a652-49e1-4c74-877d-682c26c4d278
    Remote exercise base not found in local DB, skipping...
Processing image d4b50a4d-cade-4b48-9e6c-7b1a5a822b2a
    Remote exercise base not found in local DB, skipping...
Processing image 1d3b1662-61dc-41cf-acec-ca4c86ace3eb
    Remote exercise base not found in local DB, skipping...
Processing image 2ea6fd82-46f7-4f9a-97e5-b704e6efc469
    Remote exercise base not found in local DB, skipping...
Processing image 7b392101-9c47-4693-935e-a88b1887eec5
    Remote exercise base not found in local DB, skipping...
Processing image 0fd94587-6021-4763-856e-7227f5fcba2a
    Remote exercise base not found in local DB, skipping...
Processing image 53a5e008-bc31-4ee0-9463-69a858c2ec18
    Remote exercise base not found in local DB, skipping...
*** Page 4
Processing image 0fdc1eea-07d1-4d01-8d89-6c39673dcbed
    Remote exercise base not found in local DB, skipping...
Processing image 1cdfd1d7-4cfc-424f-99bd-a851655355fc
    Remote exercise base not found in local DB, skipping...
Processing image 046ad15d-e908-43b9-91e2-b8223d4322fa
    Remote exercise base not found in local DB, skipping...
Processing image 4b3c5bf6-ea2a-4fa4-a3cb-98979c1f380a
    Remote exercise base not found in local DB, skipping...
Processing image 061cf07e-96a3-4063-8bd5-7abcdb047a99
    Remote exercise base not found in local DB, skipping...
Processing image 13fbda16-5ef6-4f48-b58c-954c3078001c
    Image not found in local DB, creating now...
    successfully saved
Processing image c9fee9d3-0b0e-40ae-a9c7-a4033781ea3b
    Image not found in local DB, creating now...
    successfully saved
Processing image e543fb73-06d0-4e1b-8645-d5706da9504a
    Remote exercise base not found in local DB, skipping...
Processing image 5f318812-108b-402c-bca3-6e409af076c7
    Remote exercise base not found in local DB, skipping...
Processing image 11db76be-b05f-4dae-8d2a-2b3135cc88b5
    Remote exercise base not found in local DB, skipping...
Processing image 75382eaf-468f-4c21-8710-6bf475d8ecc2
    Remote exercise base not found in local DB, skipping...
Processing image b2fde283-2a29-4951-8f64-442785c03078
    Remote exercise base not found in local DB, skipping...
Processing image 57e8edbe-365b-4824-b2e4-b4de197c7628
    Remote exercise base not found in local DB, skipping...
Processing image c205b132-b4f1-4e2c-b869-9b3f897bda9c
    Remote exercise base not found in local DB, skipping...
Processing image af848376-3db3-4b16-a056-4aa936d49da4
    Remote exercise base not found in local DB, skipping...
Processing image 41e5c58e-0325-4620-8d96-7372cc4dae8c
    Remote exercise base not found in local DB, skipping...
Processing image b2c5a9f9-8beb-41f7-841c-9664d22a427e
    Remote exercise base not found in local DB, skipping...
Processing image b4dfc3fb-c049-418f-855d-23ab6c39d906
    Remote exercise base not found in local DB, skipping...
Processing image 87733a46-17db-4ca1-b2dc-80c5976a5627
    Remote exercise base not found in local DB, skipping...
Processing image 492ce9c7-12cf-4378-aca4-fe008dea5dd4
    Remote exercise base not found in local DB, skipping...
*** Page 5
Processing image 3c774680-b68c-4b1c-a150-4858783661c7
    Remote exercise base not found in local DB, skipping...
Processing image c91ed07b-630b-427d-94cc-c55cdb71024a
    Remote exercise base not found in local DB, skipping...
Processing image cb9267bb-f561-49a2-94ad-fa4adebf1e27
    Remote exercise base not found in local DB, skipping...
Processing image 752caaf6-ec3d-4075-a4b3-65ec5b1922c8
    Remote exercise base not found in local DB, skipping...
Processing image 3e255a5f-b058-4a09-b0b0-70044285528a
    Remote exercise base not found in local DB, skipping...
Processing image 3c765b1e-eab9-4b61-8e2e-7d7591cb6ccb
    Remote exercise base not found in local DB, skipping...
Processing image 5e6aa692-cb40-45f5-a17c-b368c3bd2d3f
    Remote exercise base not found in local DB, skipping...
Processing image 52c61306-43c0-4f1e-bf03-13074c152dd8
    Remote exercise base not found in local DB, skipping...
Processing image 52c4434e-b5a2-4fce-af61-d997b510438a
    Remote exercise base not found in local DB, skipping...
Processing image 3d311933-e073-409b-92d3-41f3d75e8c94
    Remote exercise base not found in local DB, skipping...
Processing image c0dff0d5-618d-4739-94f9-7d3cd76bc8a1
    Remote exercise base not found in local DB, skipping...
Processing image 0dab623c-75f1-45a6-ba24-d80d42e5d284
    Remote exercise base not found in local DB, skipping...
Processing image 8fb4de34-d4df-435a-bf59-14410ebda230
    Remote exercise base not found in local DB, skipping...
Processing image dc2cf50c-6452-4a8f-91e2-6114fcc425ff
    Remote exercise base not found in local DB, skipping...
Processing image 081d1f56-c664-4493-9846-b6d6613e0ef7
    Remote exercise base not found in local DB, skipping...
Processing image 7cd81b4a-15f1-464d-96db-c2f01152fb04
    Remote exercise base not found in local DB, skipping...
Processing image 9d5d511e-d0a1-45e7-b656-07b0b86541d4
    Remote exercise base not found in local DB, skipping...
Processing image a1b5b12d-06ab-4e80-93bc-352da6aec7f5
    Remote exercise base not found in local DB, skipping...
Processing image 545a71c9-440d-442d-b772-1458eb4f1125
    Remote exercise base not found in local DB, skipping...
Processing image bec83f17-2060-4bee-8a02-78db230568bf
    Remote exercise base not found in local DB, skipping...
*** Page 6
Processing image dd63c466-ea7e-47f4-b1b2-8a50b4656dfc
    Remote exercise base not found in local DB, skipping...
Processing image 01a05758-9b0b-4d9c-b5a6-80b9df6bd26a
    Remote exercise base not found in local DB, skipping...
Processing image 1983b6be-1784-4ad3-a05c-7e4b34d9878f
    Remote exercise base not found in local DB, skipping...
Processing image 239d43a2-b86f-4dc7-aab2-27c8c2f7de47
    Remote exercise base not found in local DB, skipping...
Processing image f8d23bc0-4b42-40fb-aa01-970fb573a212
    Remote exercise base not found in local DB, skipping...
Processing image d7c5c697-8a93-4d69-8c9d-a919cb4e1f77
    Remote exercise base not found in local DB, skipping...
Processing image a7d82572-ca40-4616-a13d-a359d7efae20
    Remote exercise base not found in local DB, skipping...
Processing image aa0ff663-f593-465e-9fce-c01b77c6eb9c
    Remote exercise base not found in local DB, skipping...
Processing image c6464fb3-1924-4ff1-adfa-fd36da9b5d13
    Remote exercise base not found in local DB, skipping...
Processing image abfc7700-fadf-4f2d-ac84-e045e590a2fe
    Remote exercise base not found in local DB, skipping...
Processing image 6a770e5d-cd62-4754-a18c-eebe2103d7c5
    Remote exercise base not found in local DB, skipping...
Processing image 692c598c-0493-42a5-be8b-b9d2e9adcd00
    Remote exercise base not found in local DB, skipping...
Processing image 2e69c005-b241-4806-8557-fc5a4d5ee44d
    Remote exercise base not found in local DB, skipping...
Processing image 30b2631d-d7ec-415c-800b-7eb082314c0a
    Remote exercise base not found in local DB, skipping...
Processing image a3073a56-3099-42e6-8964-7a19fb3f6237
    Remote exercise base not found in local DB, skipping...
Processing image 611eef29-39f3-4a8b-ae37-fb78abfa1a11
    Remote exercise base not found in local DB, skipping...
Processing image 01dd27bc-17d5-48c9-840b-c77418d207cd
    Remote exercise base not found in local DB, skipping...
Processing image 4744270a-73a0-4e45-8af8-52df29cc14fb
    Remote exercise base not found in local DB, skipping...
Processing image a6d6d740-eb6c-4a0d-ac28-72ad03abf76a
    Remote exercise base not found in local DB, skipping...
Set site URL to http://localhost
Using gunicorn...
[2023-02-06 05:27:00 +0000] [88] [INFO] Starting gunicorn 20.1.0
[2023-02-06 05:27:00 +0000] [88] [INFO] Listening at: http://0.0.0.0:8000 (88)
[2023-02-06 05:27:00 +0000] [88] [INFO] Using worker: sync
[2023-02-06 05:27:00 +0000] [89] [INFO] Booting worker with pid: 89`

**Comment by rolandgeider** [comment]
Hi! Just update the image, newer ones also update the available languages before fetching the exercises. Also note that we just merged the exercise database of feeel, another floss fitness app, so the sync process might take a bit longer.

(closing the issue, if the error persists, just re open)

**Comment by hherrera1229** [comment]
Thank for the reply. I am using the latest image tags wger/server:latest. Is that not the latest image?

**Comment by hherrera1229** [comment]
Thanks for the reply! Exercises do appear to be syncing now but still getting an error. Turned on Django_Debug=True and I'm getting this as the error:

`Environment:


Request Method: GET
Request URL: http://XXX.XXX.X.XX/en/software/features

Django Version: 4.1.5
Python Version: 3.10.6
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.messages',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.staticfiles',
 'django_extensions',
 'storages',
 'wger.config',
 'wger.core',
 'wger.mailer',
 'wger.exercises',
 'wger.gym',
 'wger.manager',
 'wger.nutrition',
 'wger.software',
 'wger.utils',
 'wger.weight',
 'wger.gallery',
 'wger.measurements',
 'captcha',
 'django.contrib.sitemaps',
 'easy_thumbnails',
 'compressor',
 'crispy_forms',
 'rest_framework',
 'rest_framework.authtoken',
 'django_filters',
 'rest_framework_simplejwt',
 'django_bootstrap_breadcrumbs',
 'corsheaders',
 'axes',
 'simple_history',
 'django_email_verification',
 'actstream',
 'fontawesomefree')
Installed Middleware:
('corsheaders.middleware.CorsMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'wger.utils.middleware.JavascriptAJAXRedirectionMiddleware',
 'wger.utils.middleware.WgerAuthenticationMiddleware',
 'wger.utils.middleware.RobotsExclusionMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'simple_history.middleware.HistoryRequestMiddleware',
 'axes.middleware.AxesMiddleware')



Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/wger/src/wger/software/views.py", line 37, in features
    return render(request, 'features.html', context)
  File "/usr/local/lib/python3.10/dist-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.10/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.10/dist-packages/django/template/backends/django.py", line 62, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 173, in render
    with context.bind_template(self):
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.10/dist-packages/django/template/context.py", line 254, in bind_template
    updates.update(processor(self.request))
  File "/home/wger/src/wger/utils/context_processor.py", line 71, in processor
    'custom_header': get_custom_header(request),
  File "/home/wger/src/wger/utils/context_processor.py", line 111, in get_custom_header
    global_gymconfig = GymConfig.objects.get(pk=1)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(

Exception Type: DoesNotExist at /en/software/features
Exception Value: GymConfig matching query does not exist.`

**Comment by rolandgeider** [comment]
Why does it complain about GymConfig now? That's something we haven't touched in years. Besides pulling new images you didn't change anything rihgt?

**Comment by hherrera1229** [comment]
Not much. 

> I changed the port used by nginx, followed the example in the docs and only changed it in nginx didn't touch the port in the wger-server container. 

> My docker network was named web so I changed the name of the service of wger-server from web to wger and made sure I updated the "depends on" in the other containers. 

> I moved the prod.env variables into the main compose file but that was mostly in case I needed to toggle things on/off quickly, all the options are the same as the provided example except for my email and timezone.

> Mapped my volumes to different folders then the default setup.

That's about it. Would any of that cause this error?

**Comment by hherrera1229** [comment]
Gave up on trying to run this on my existing docker instance. Tried running it on a raspberry pi with a fresh docker install with no other containers on it except for portainer, all settings exactly as provided in the docker-compose file and it still doesn't run as it should. The static folder remains empty for some reason. Going into the docker container shell and navigating to the /home/wger/static folder within the wger-server container and it is indeed empty. Not sure if it's a permissions thing, the media folder seems to populate correctly. Wger-nginx logs show a bunch of missing images and stuff.

**Comment by rolandgeider** [comment]
I think I know what happens. If you renamed the web service, you need to update the nginx.conf as well (where it says web:8000). BTW, does having a network called web really make problems when the service has the same name?

**Comment by hherrera1229** [comment]
No I changed it to wger there too. I'll try deploying it as a completely separate stack only changing the port and mapping volumes and see if that works.

**Comment by rolandgeider** [comment]
Ah alright. Now that I you mention it, it wouldn't explain why it didn't collect any static files to the folder (everything in there is generated/ copied from other places, BTW, no need to backup it or anything, just make sure it can write to it)

**Comment by hherrera1229** [comment]
Yeah it's writable, media folder seems to populate just fine. I found some of the missing images just browsing the GitHub repo and moved them over to the static folder manually, restarted the containers, and headed on over to the page and some of the images did show up. Missing a whole bunch more though and css files, not sure moving them all manually is possible.

**Comment by rolandgeider** [comment]
no, you need to copy the static files from all the django apps, not only ours. Plus every time there is an update. You can manually run `docker compose exec web python3 manage.py collectstatic` and see if there are any errors (this happens every time during startup anyway)

**Comment by hherrera1229** [comment]
Well that worked, no errors when running that command. Everything looks normal now. Looking back at the logs I don't see any errors as the container is building and I rebuilt it twice, once changing nothing from the default and another only having changed the volumes. 

I'll keep troubleshooting trying to get it running on my main docker instance. At least the stakes are lower since I have this instance running on an RPi. Thank you for the help!
