### ISSUE TITLE
Workout - cannot add untranslated excercises

### ISSUE THREAD

**Issue by sathrudi** [wger-project/docker#51]
## Problem: 
When adding excercises to a workout and having language set to Czech, I can't find excercises that are not translated. Workaround is switching to English, no problem there.

Here is an excersise not translated to czech.
![image](https://user-images.githubusercontent.com/85929245/218394897-1f142a27-8bdc-4d70-958a-39ab0ef6d84e.png)

Here is a screenshot of me trying to add this excersise to a workout.
![image](https://user-images.githubusercontent.com/85929245/218396231-5fd53ee1-aec9-4775-bf46-bd341acb3473.png)

## Environment: 
I'm running the latest release in docker, excercises pullled this morning. My language is mostly set to Czech, but due to some problems, I switch to English.

**Comment by rolandgeider** [comment]
Hi! yes you are right, when you switch the language currently only the exercises in that language are searched. I'm working on making this configurable

Closing here since this was already reported here https://github.com/wger-project/wger/issues/1238
