### ISSUE TITLE
[Bug] Wger command "load-online-fictures" not working.

### ISSUE THREAD

**Issue by Leolele99** [wger-project/docker#53]
**Version:**
Latest

**Description:**
When executing the command `wger load-online-fixtures` within the container, the command seems to be run, but never finishes.
The console reports back
`Downloading fixture data from https://github.com/wger-project/data/raw/master/fixtures/ingredients.json.zip...`
but afterwards nothing happens.

To test it, I left it running overnight, but nothing changes. 
Ingredients are also not added to the setup.

**Comment by rolandgeider** [comment]
From the discord discussion, this seems to be a problem with docker compse timeouting some requests, closing here. If the problem persists, feel free to reopen
