### ISSUE TITLE
Missing linux/amd64 in wger/server:latest?

### ISSUE THREAD

**Issue by anarion80** [wger-project/docker#57]
Hello.

My CI woke me up today with the following error when pulling the latest image for wger/server:

```
fatal: [instance]: FAILED! => {"changed": false, "msg": "Error pulling wger/server - code: None message: no matching manifest for linux/amd64 in the manifest list entries"}
```

and looks like the `latest` version is indeed only `linux/arm64`. Only `2.1-dev` tag contains both arm64 and amd64.

Is this intentional? Only ARM now for latest?

**Comment by rolandgeider** [comment]
Hi! No, this was a bug, the images shoud build regularly again
