### ISSUE TITLE
Error parsing template

### ISSUE THREAD

**Issue by los2pollos** [wger-project/docker#7]
Hi everyone, I keep getting this error whenever I launch the server. I experience a few problems related to translation and users management as an admin, but besides from that, no problem with syncing with the Android App.

![image](https://user-images.githubusercontent.com/66679495/121506487-0c3d4300-c9e4-11eb-9f11-095ba8fabaa5.png)

**Comment by rolandgeider** [comment]
Seems a dependency is missing

**Comment by rolandgeider** [comment]
This should be fixed (please note that you need to use the latest docker-comppose and then pull the newest version of the images)
