### ISSUE TITLE
CSRF error

### ISSUE THREAD

**Issue by stutz64** [wger-project/docker#71]
![image](https://github.com/wger-project/docker/assets/74467232/78676888-d1b1-45a0-a486-1054b9094682)

Dear Sir or Madam, unfortunately I receive a CSRF error when I use wger ​​via a s[elf-hosted gateway](https://github.com/fractalnetworksco/selfhosted-gateway).

The URL I have is https://workous.domain.xyz

I didn't change the static and media urls in the config file. I tested it once with the standard static and media urls and once with my domain.

Both times I received the same error message.

Do you know what the problem could be?

Access to the web interface is possible, but logging in does not work because of the csrf error.

**Comment by stutz64** [comment]
works. Forgot to add the domain to the csrf allowed domains in the prod.env file.

**Comment by rolandgeider** [comment]
glad you got it to work! Will close here
