### ISSUE TITLE
Error when attempting login 'ip-address' lockout parameter is not allowed. 

### ISSUE THREAD

**Issue by Ujeeee** [wger-project/docker#74]
![image](https://github.com/wger-project/docker/assets/76468751/171e0523-806e-44aa-bff5-d621a9bbbcdf)

<html>
<body>
<h1 style="padding: 0px; margin: 0px; font-weight: normal; color: rgb(0, 0, 0); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">ValueError at /en-gb/user/login</h1><pre class="exception_value" style="padding: 0px; margin: 10px 0px; font-size: 1.5em; white-space: pre-wrap; word-break: break-word; font-family: sans-serif; color: rgb(87, 87, 87); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">'ip-address' lockout parameter is not allowed. Allowed parameters: username, ip_address, user_agent</pre>
Request Method: | POST
-- | --
http://192.168.0.100/en-gb/user/login
4.2.6
ValueError
'ip-address' lockout parameter is not allowed. Allowed parameters: username, ip_address, user_agent
/usr/local/lib/python3.10/dist-packages/axes/helpers.py, line 282, in get_client_parameters
django.contrib.auth.views.LoginView
/usr/bin/python3
3.10.12
['/home/wger/src',  '/usr/local/bin',  '/usr/lib/python310.zip',  '/usr/lib/python3.10',  '/usr/lib/python3.10/lib-dynload',  '/home/wger/.local/lib/python3.10/site-packages',  '/home/wger/src',  '/usr/local/lib/python3.10/dist-packages',  '/usr/lib/python3/dist-packages']
Sun, 17 Dec 2023 12:53:58 +0700

</body>
</html>

**Comment by bbkz** [comment]
oy... very bad, sorry for that i'll post a pull request fixing that bad default.

Meanwhile you can set the following in your `env` file:

```
AXES_LOCKOUT_PARAMETERS="ip_address"
```

**Comment by rolandgeider** [comment]
PR is merged, docker images with the correct default should be available shortly. Will update the prod.env so that it's clear what options are available, closing here
