### ISSUE TITLE
Error web_server unhealty

### ISSUE THREAD

**Issue by andreacocci95** [wger-project/docker#75]
Hi, I'm trying to install wger by docker compose file. I follow all the guide and I receive an error while web_server is starting.

```
yarn install v1.22.21
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error Error: getaddrinfo EAI_AGAIN codeload.github.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

What can I do? Thanks!

**Comment by rolandgeider** [comment]
it seems the application isn't able to download some of the dependencies, is there anything preventing docker from reaching the internet?

**Comment by andreacocci95** [comment]
Seems this but I don't know why it doesn't have connectivity. I used the docker-compose.yml with the config in this repo. Other containers works without problem.

**Comment by andreacocci95** [comment]
Ok, the problem is that I have as DNS a PiHole instance in another container. The container with Wger doesn't see the Pihole container so it not have connection. I override dns address on docker compose file under wger_server as described here: https://stackoverflow.com/a/41717827
Now it works.
