### ISSUE TITLE
load-online-fixtures hanging

### ISSUE THREAD

**Issue by ebwinters** [wger-project/docker#76]
I have an instance running on docker. Everything is working fine except when I execute `sudo docker compose exec web python3 wger load-online-fixtures` I get:

<img width="682" alt="image" src="https://github.com/wger-project/docker/assets/4297028/f43ee69e-fc96-4033-9e05-82cd070e2b9e">

and it just hangs  for 10 minutes before I cut it off. Any workaround here?

**Comment by rolandgeider** [comment]
While loading those fixtures does take some time, it should definitely finish after some time. Did you get some error after that (like some network timeout or something)?

**Comment by ebwinters** [comment]
> While loading those fixtures does take some time, it should definitely finish after some time. Did you get some error after that (like some network timeout or something)?

Letting it run for ~5min today worked . Must have been my net connection at the time, closing this. Thanks!
