### ISSUE TITLE
DETAIL:  Key (language_id)=(4) is not present in table "core_language".

### ISSUE THREAD

**Issue by witchent** [wger-project/docker#78]
While trying to update ecercises (using ``podman exec wger python3 manage.py sync-exercises``) I get the following error:

```
Feb 12 02:30:05 hostname sh[410879]: updated exercise ea63d85c-8579-4dda-b99f-c4c8930f9af6
Feb 12 02:30:05 hostname sh[410879]: Traceback (most recent call last):
Feb 12 02:30:05 hostname sh[410879]:   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/bas>
Feb 12 02:30:05 hostname sh[410879]:     return self.connection.commit()
Feb 12 02:30:05 hostname sh[410879]: psycopg2.errors.ForeignKeyViolation: insert or update on table "exercises_e>
Feb 12 02:30:05 hostname sh[410879]: DETAIL:  Key (language_id)=(4) is not present in table "core_language".
Feb 12 02:30:05 hostname sh[410879]: The above exception was the direct cause of the following exception:
Feb 12 02:30:05 hostname sh[410879]: Traceback (most recent call last):
Feb 12 02:30:05 hostname sh[410879]:   File "/home/wger/src/manage.py", line 24, in <module>
Feb 12 02:30:05 hostname sh[410879]:     execute_from_command_line(sys.argv)
Feb 12 02:30:05 hostname sh[410879]:   File "/usr/local/lib/python3.10/dist-packages/django/core/management/__in>
Feb 12 02:30:05 hostname sh[410879]:     utility.execute()
Feb 12 02:30:05 hostname sh[410879]:   File "/usr/local/lib/python3.10/dist-packages/django/core/management/__in>
Feb 12 02:30:05 hostname sh[410879]:     self.fetch_command(subcommand).run_from_argv(self.argv)
Feb 12 02:30:05 hostname sh[410879]:   File "/usr/local/lib/python3.10/dist-packages/django/core/management/base>
Feb 12 02:30:05 hostname sh[410879]:     self.execute(*args, **cmd_options)
Feb 12 02:30:05 hostname sh[410879]:   File "/usr/local/lib/python3.10/dist-packages/django/core/management/base>
Feb 12 02:30:05 hostname sh[410879]:     output = self.handle(*args, **options)
Feb 12 02:30:05 hostname sh[410879]:   File "/home/wger/src/wger/exercises/management/commands/sync-exercises.py>
Feb 12 02:30:05 hostname sh[410879]:     sync_exercises(self.stdout.write, self.remote_url, self.style.SUCCESS)
Feb 12 02:30:05 hostname sh[410879]:   File "/home/wger/src/wger/exercises/sync.py", line 104, in sync_exercises
Feb 12 02:30:05 hostname sh[410879]:     translation, translation_created = Exercise.objects.update_or_create(
Feb 12 02:30:05 hostname sh[410879]:   File "/usr/local/lib/python3.10/dist-packages/django/db/models/manager.py>
Feb 12 02:30:05 hostname sh[410879]:     return getattr(self.get_queryset(), name)(*args, **kwargs)
Feb 12 02:30:05 hostname sh[410879]:   File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py",>
Feb 12 02:30:05 hostname sh[410879]:     with transaction.atomic(using=self.db):
Feb 12 02:30:05 hostname sh[410879]:   File "/usr/local/lib/python3.10/dist-packages/django/db/transaction.py", >
Feb 12 02:30:05 hostname sh[410879]:     connection.commit()
Feb 12 02:30:05 hostname sh[410879]:   File "/usr/local/lib/python3.10/dist-packages/django/utils/asyncio.py", l>
Feb 12 02:30:05 hostname sh[410879]:     return func(*args, **kwargs)
Feb 12 02:30:05 hostname sh[410879]:   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/bas>
Feb 12 02:30:05 hostname sh[410879]:     self._commit()
Feb 12 02:30:05 hostname sh[410879]:   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/bas>
Feb 12 02:30:05 hostname sh[410879]:     with debug_transaction(self, "COMMIT"), self.wrap_database_errors:
Feb 12 02:30:05 hostname sh[410879]:   File "/usr/local/lib/python3.10/dist-packages/django/db/utils.py", line 9>
Feb 12 02:30:05 hostname sh[410879]:     raise dj_exc_value.with_traceback(traceback) from exc_value
Feb 12 02:30:05 hostname sh[410879]:   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/bas>
Feb 12 02:30:05 hostname sh[410879]:     return self.connection.commit()
Feb 12 02:30:05 hostname sh[410879]: django.db.utils.IntegrityError: insert or update on table "exercises_exerci>
Feb 12 02:30:05 hostname sh[410879]: DETAIL:  Key (language_id)=(4) is not present in table "core_language".
```

Any idea what might be happening here or how to fix this?

**Comment by rolandgeider** [comment]
Sorry for the late reply! Is this on a new install? I have seen something similar happen when for some reason the database service is not ready when the application tries to bootstrap itself. I would recommend deleting the db volume, starting the service first manually and then the rest (this would only be necessary the very first time, not later)

**Comment by witchent** [comment]
Oh I somehow missed the notification for this error.
I cannot reproduce it right now so I'm closing this. Thanks for your answer

**Comment by Victorivus** [comment]
I am getting a similar error with another language (**id=16**)

I run: `docker compose exec web python3 manage.py sync-exercises`

it does all the following steps with no problems:

```
*** Synchronizing languages...
done!

*** Synchronizing categories...
done!

*** Synchronizing muscles...
done!

*** Synchronizing equipment...
done!

*** Synchronizing licenses...
done!
```

And when it starts `Synchronizing exercises..`, after updating a few:
```
django.db.utils.IntegrityError: insert or update on table "exercises_exercise" violates foreign key constraint "exercises_exercise_language_id_9675c687_fk_core_language_id"
DETAIL:  Key (language_id)=(16) is not present in table "core_language".
```

![image](https://github.com/wger-project/docker/assets/18736740/368b04b8-3752-4eb4-a4ae-cccc668b7723)


It indeed does not exist in the DB:
```
docker exec -ti wger_db psql -U wger
#  select * from core_language;
```

![image](https://github.com/wger-project/docker/assets/18736740/e1107180-f1db-4e58-b5a0-e5b1a5834197)

**Comment by Victorivus** [comment]
Thanks for the answer @bbkz , I did and there were 2 exercises with no translation deleted them with the script option and same problem.

I tried to add manually a language with the missing id (16) and it worked (it inserted the exercise) but then failed with the same error complaining about another missing language (id 7 I believe but not sure, I don't have the log).

after the language sync, should the table shown in my above message be complete? or is it normal to have missing ids?

**Comment by bbkz** [comment]
Hi, I don't know I never had the time to have a deep look into the code.

I remember having the same problem once, but don't remember the cause of it.

Did all your Django database migration run. `manage.py migrate`

**Comment by rolandgeider** [comment]
ohh I know what's happening here. When we sync the new languages, we simply create new entries in the db if the short name (fr, es, etc.) is not known. If for some reason you had some and deleted them, added new ones or something, the new languages have different IDs that what the API returns, that's why the IDs have gaps in the screenshot you posted.

The solution would then be to map the language IDs we get from the server to the local ones (forcing the IDs would break local instances where the admin had manually added new ones)...

As a fix for your specific problem, running `python manage.py loaddata languages` should overwrite everything with the correct data (including IDs)

**Comment by rolandgeider** [comment]
yes, empty them first and then do the loaddata. But this is still not a good solution since postgres will still insert new entries at higher IDs, so you'd potentially get problems in the future, you'd also need to reset the sequence in the db.

I have created an issue for the sync problem https://github.com/wger-project/wger/issues/1667 If you want to give it a try go ahead! (and feel free to ping me to discuss stuff)
