### ISSUE TITLE
Newb-tube question

### ISSUE THREAD

**Issue by Roskafarian** [wger-project/docker#8]
First time using docker to install a program sequence such as this one. I may need a little hand-holding or the right repo to follow instructions from. Anyone have the 411 on that?

**Comment by rolandgeider** [comment]
Hi!

While docker is really easy compared to installing the application "by hand", you'll still need to manage it a bit. (Isn't the hosted version an option for you?) But basically the steps are

1) Install docker for your operating system
2) Clone this repository somewhere (you will need to install git for this)
3) Open a terminal and go to the folder where you cloned it
4) Start the docker images with the commands from the readme

This will spin up the containers needed to start using the application, but you will need to take care of pulling updates
