### ISSUE TITLE
Error: for celery_worker. `wger_server` is unhealthy. DB authentication issue?

### ISSUE THREAD

**Issue by gagestinson** [wger-project/docker#87]
I have been struggling with this for a while now. I tried making my own volumes so they could be mounted to a different location on my host machine but then I got this error. I then tried running the `docker-compose.yml` file exactly as the repo has it by default along with all of the stuff in the config directory. (Everything in the compose file is the default except the host post for nginx since I already have port 80 in use)

I am getting the following output in the terminal after running `docker-compose up -d`:
```
Creating network "wger_network" with the default driver
Creating wger_cache ... done
Creating wger_db    ... done
Creating wger_server ... done
Creating wger_nginx  ... done

ERROR: for celery_worker  Container "8f69fc159297" is unhealthy.
ERROR: Encountered errors while bringing up the project.
```

Running `docker ps | grep 8f69fc159297` I get the output:
```
8f69fc159297   wger/server:latest          "/home/wger/entrypoi…"   5 minutes ago   Up 5 minutes (unhealthy)     8000/tcp

               wger_server
```

Using Portainer I look into the logs of `wger_server` and this is what is shown:
```
.....
  File "/usr/local/lib/python3.10/dist-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/base.py", line 270, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/postgresql/base.py", line 275, in get_new_connection
    connection = self.Database.connect(**conn_params)
  File "/usr/local/lib/python3.10/dist-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: connection to server at "db" (172.31.0.2), port 5432 failed: FATAL:  password authentication failed for user "wger"
Using gunicorn...
[2024-06-12 19:29:39 +0000] [43] [INFO] Starting gunicorn 22.0.0
[2024-06-12 19:29:39 +0000] [43] [INFO] Listening at: http://0.0.0.0:8000 (43)
[2024-06-12 19:29:39 +0000] [43] [INFO] Using worker: sync
[2024-06-12 19:29:39 +0000] [44] [INFO] Booting worker with pid: 44
INFO 2024-06-12 21:29:40,038 apps AXES: BEGIN version 6.4.0, blocking by ip_address
ERROR 2024-06-12 21:29:41,714 log Internal Server Error: /
ERROR 2024-06-12 21:29:51,853 log Internal Server Error: /
ERROR 2024-06-12 21:30:02,012 log Internal Server Error: /
ERROR 2024-06-12 21:30:12,187 log Internal Server Error: /
ERROR 2024-06-12 21:30:22,355 log Internal Server Error: /
.....
```

So it looks like this is maybe some kind of authentication issue? I am not familiar with databases in the slightest so I am not sure if this is the issue or if this is just another thing on top of my problem. I am just confused since this passwords and usernames are the default that the repo uses but I am getting this error. Any suggestions?

**Comment by rolandgeider** [comment]
that does indeed look like an auth error, which is weird (specially since the way celery_worker connects is the exact same as the web image). Just to be sure, can you nuke all the volumes, containers etc and try again? Obviously the nginx port isn't a problem

**Comment by gagestinson** [comment]
Wow. Cannot believe it was that simple. Thank you for the help. Like I said I know basically nothing about databases and am not too familiar with docker from CLI. I was trying to use Portainer at first but that did not work at all so I just went with the default way. Thanks!

**Comment by rolandgeider** [comment]
the web service is supposed to be unhealthy? I mean if it works, it works. But I can take a look

**Comment by gagestinson** [comment]
It is supposed to be unhealthy? Are you able to elaborate?

It was a little strange, I was getting that issue with the `celery_worker` again in the terminal but after just running `docker-compose down` and then `docker-compose up -d` again a couple times it all started working okay. I am starting to have another DB authentication issue tho, but I will search the issues before posting a new one if necessary.

**Comment by rolandgeider** [comment]
no, no, it shouldn't be unhealthy, but there might be a problem with the health check. Also, I know from what others have tried that if instead of the volumes you map folders, you will need to tweak file and folder permissions so that everything works fine (but those shouldn't cause authentication issues, or if they do, then also in the web service, not only celery)

**Comment by gagestinson** [comment]
yea I am presently having that as one of my issues. Is there a previous post about this specifically for me to read?

**Comment by deboy69** [comment]
Getting the same error. Any update on this?

**Comment by deboy69** [comment]
> Getting the same error. Any update on this?

had to chmod 777 -R /static folder for it to work without the permissions error.
