### ISSUE TITLE
Confused with which image I should be using

### ISSUE THREAD

**Issue by sseneca** [wger-project/docker#9]
The main repo [says](https://github.com/wger-project/wger#production):

> If you want to host your own instance, take a look at the provided docker compose file. This config will persist your database and uploaded images

But then the docker compose file uses `wger/devel`, which in [its description](https://hub.docker.com/r/wger/devel) says:

> Please note that this image is intended for development

And then says to check out the docker compose file instead.

The other images (`wger/apache` and `wger/base`) are both also apparently not intended for production usage. So what am I meant to do if I want to deploy a production instance of wger via docker?

**Comment by rolandgeider** [comment]
Hi! You are right that the descriptions are somewhat confusing. This docker compose configures the dev image so that it doesn't use django's development server, but a real one. I had planned on renaming them so that it's more obvious what they do (e.g. "apache" to "demo", but I haven't gotten around to

**Comment by sseneca** [comment]
Ah okay, so it's best to stick with the devel image. With tag then is best? The latest stable release for wger is `2.0`, but there is no `2.0` tag (as far as I can tell), only `2.0-dev`.

**Comment by rolandgeider** [comment]
Just stick with this docker compose, it will use the latest version. The images are automatically built from master, which is (or should 😅) always be stable and usable, releases happen only once in a while

**Comment by sseneca** [comment]
Alright, will do, thanks for the info!
