### ISSUE TITLE
Missing static CSS and JS files

### ISSUE THREAD

**Issue by seyfeb** [wger-project/docker#92]
I get several 404s on the website because static files are missing. I have not changed the volumes, they are not locally mounted

Missing files are:

`popper.js`
`bootstrap.bundle.min.js`
`bootstrap.compiled.css`
`all.css`

I do not see the css files in the container at `/home/wger/static/css/`. There are only the files and folders `bootstrap-custom.css`, `images/`  `landing_page.css` `react-simple-wysiwyg.css`, and `workout-manager.css`.

Any ideas why this could be the case? I noticed one warning in the logs:

```
wger_server  | warning " > bootstrap@5.3.3" has unmet peer dependency "@popperjs/core@^2.11.8".
```

but I'm not sure this has something to do with it.

<details>

<summary>Part of the logs</summary>

```
wger_server  | yarn install v1.22.22
wger_server  | [1/5] Validating package.json...
wger_server  | [2/5] Resolving packages...
wger_server  | [3/5] Fetching packages...
wger_server  | [4/5] Linking dependencies...
wger_server  | warning " > bootstrap@5.3.3" has unmet peer dependency "@popperjs/core@^2.11.8".
wger_server  | [5/5] Building fresh packages...
wger_server  | Done in 3.02s.
wger_server  | yarn run v1.22.22
wger_server  | $ sass wger/core/static/scss/main.scss:wger/core/static/yarn/bootstrap-compiled.css
wger_server  | Done in 3.55s.
</details>
```

**Comment by rolandgeider** [comment]
hi! mhh, the bootstrap-compiled.css is generated during startup and your logs show that they are compiled correctly. The same with the yarn folder which should be there. Just to be sure, can you restart the service?

**Comment by seyfeb** [comment]
I can stop an start the web (wger_server) container without any difference. Or are you referring to something else?

Inside the container which commands should create the files? I could try to create them manually just to see if it works.

Is my assumption correct that they should be located at `/home/wger/static/css/yarn` in the web (wger_server) container?

**Comment by rolandgeider** [comment]
yes, I was referring to the container. You can try doing the steps manually, perhaps they will work (or you will see an error message and see why this didn't work). Just do `yarn install` and `yarn build:css:sass`. This should download everything and you should at least see those files in wger/core/static/...

**Comment by seyfeb** [comment]
This seems to work at least

<details>

<summary>Console output</summary>

```
wger@365b38451a32:~/src$ yarn install
yarn install v1.22.22
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 0.22s.
wger@365b38451a32:~/src$ yarn build:css:sass
yarn run v1.22.22
$ sass wger/core/static/scss/main.scss:wger/core/static/yarn/bootstrap-compiled.css
Done in 4.28s.
wger@365b38451a32:~/src$ ls wger/core/static/
css  fonts  images  js  react  scss  yarn
wger@365b38451a32:~/src$ ls wger/core/static/yarn/
bootstrap                   d3-array    d3-delaunay  d3-force        d3-polygon          d3-shape        datatables                 get-size        popper.js          yarn
bootstrap-compiled.css      d3-axis     d3-dispatch  d3-format       d3-quadtree         d3-time         delaunator                 iconv-lite      robust-predicates
bootstrap-compiled.css.map  d3-brush    d3-drag      d3-geo          d3-random           d3-time-format  desandro-matches-selector  internmap       rw
commander                   d3-chord    d3-dsv       d3-hierarchy    d3-scale            d3-timer        devbridge-autocomplete     jquery          safer-buffer
components-font-awesome     d3-color    d3-ease      d3-interpolate  d3-scale-chromatic  d3-transition   ev-emitter                 masonry-layout  Sortable
d3                          d3-contour  d3-fetch     d3-path         d3-selection        d3-zoom         fizzy-ui-utils             outlayer        @types
wger@365b38451a32:~/src$
```

</details>

After manually copying the files to the server directory, they are served as expected 🤔 

`cp -r wger/core/static/yarn/ /home/wger/static/`

**Comment by seyfeb** [comment]
I deleted all containers and volumes and started from scratch. No data at all was in `/home/wger/static/`, so I checked the script and noticed that, with `DJANGO_DEBUG=True` set no data is copied to the shared static directory.

I had set the debug option because I had other issues earlier and thought that it would probably provide me with more details in the logs. It was not clear to me that serving the webpage would not work _at all_ with this option! Maybe I missed it in the docs but if not it might be helpful to explain what the setting entails :)

I have no idea, why previously the static files were partially available in the static directory. This makes no sense and unfortunately I'm not able to reproduce this. However, without `DJANGO_DEBUG=True` everything works fine.

**Comment by rolandgeider** [comment]
carefull with this, setting debug to true uses django's development server which is not made for this! During developemnt the server will also serve static files, but during production this has to be done by another process, that's why the files are all copied to a single location, nginx will serve that folder. Also, if errors occur, the full configuration will be shown.

I also can't explain why only some files were not copied over, we use the same docker setup for the hosted version and never had a problem

**Comment by seyfeb** [comment]
It's working now, so I guess this can be ignored! Thanks for your help, anyway!
